/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    offers: Offer;
    'offer-packs': OfferPack;
    destinations: Destination;
    hotels: Hotel;
    testimonials: Testimonial;
    faqs: Faq;
    features: Feature;
    'booking-steps': BookingStep;
    reservations: Reservation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'offer-packs': OfferPacksSelect<false> | OfferPacksSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    'booking-steps': BookingStepsSelect<false> | BookingStepsSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'gallery-page': GalleryPage;
    'home-page': HomePage;
    'booking-process-content': BookingProcessContent;
  };
  globalsSelect: {
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'booking-process-content': BookingProcessContentSelect<false> | BookingProcessContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  cloudinaryPublicId?: string | null;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: string;
  title: string;
  /**
   * Auto-generated from title if left blank
   */
  slug?: string | null;
  destination: string;
  country: string;
  /**
   * Ancien champ emoji. Utilisez plutôt 'Image du drapeau' ci-dessous.
   */
  flag?: string | null;
  flagMedia?: (string | null) | Media;
  flagUrl?: string | null;
  region?: ('Turquie' | 'Europe' | 'Moyen-Orient' | 'Asie' | 'Afrique' | 'Océanie' | 'Omra') | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainImage?: (string | null) | Media;
  mainImageUrl?: string | null;
  /**
   * Les 4 images affichees sur la page detail de l'offre : 1 grande image + 3 images laterales.
   */
  detailGallery?: {
    main?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
    };
    side01?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
    };
    side02?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
    };
    side03?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
    };
  };
  galleryImages?:
    | {
        image?: (string | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "18-25 janvier"
   */
  dates?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  durationDays?: number | null;
  durationNights?: number | null;
  /**
   * e.g. "7 Jours"
   */
  duration?: string | null;
  /**
   * Prix affiché sur la carte de l'offre. e.g. "84 000"
   */
  price: string;
  /**
   * Prix de base de l'offre sans hôtel spécifique.
   */
  priceAmount?: number | null;
  currency?: string | null;
  /**
   * Associez un hôtel à cette offre et définissez son prix directement ici.
   */
  hotels?:
    | {
        hotel: string | Hotel;
        /**
         * e.g. "84 000 DA"
         */
        priceLabel?: string | null;
        /**
         * Utilisé pour les calculs de réservation.
         */
        priceAmount?: number | null;
        childPriceBrackets?:
          | {
              /**
               * Ex: "2 – 4 ans"
               */
              label: string;
              minAge?: number | null;
              maxAge?: number | null;
              priceAmount: number;
              /**
               * Ex: "15 000 DA"
               */
              priceLabel?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Coup de coeur", "Nouveau"
   */
  tag?: string | null;
  badge?: string | null;
  badgeVariant?: ('info' | 'warning' | 'danger') | null;
  status?: ('available' | 'almost-full' | 'sold-out') | null;
  showOnHomepage?: boolean | null;
  departureLocation?: string | null;
  location?: string | null;
  time?: string | null;
  metaDates?: string | null;
  metaDuration?: string | null;
  priceSummary?: string | null;
  priceCard?: {
    description?: string | null;
    travellersLabel?: string | null;
    defaultAdults?: number | null;
    travellersText?: string | null;
    detailsTitle?: string | null;
    totalLabel?: string | null;
    reserveButtonLabel?: string | null;
    confirmationText?: string | null;
  };
  numberOfDays?: number | null;
  inclusions?:
    | {
        item: string;
        icon?: ('check' | 'plane' | 'hotel' | 'transfer' | 'assistance' | 'meal' | 'map' | 'calendar') | null;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  program?:
    | {
        /**
         * e.g. "JOUR 1"
         */
        dayLabel: string;
        title: string;
        description?: string | null;
        locations?:
          | {
              place: string;
              id?: string | null;
            }[]
          | null;
        meals?:
          | {
              /**
               * e.g. "Petit-déjeuner", "Dîner"
               */
              meal: string;
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image?: (string | null) | Media;
              imageUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        isLast?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: string;
  name: string;
  /**
   * Description courte de l'hôtel
   */
  description?: string | null;
  stars?: number | null;
  rating?: number | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  /**
   * e.g. "18-25 janvier 2026"
   */
  dates?: string | null;
  /**
   * Géré automatiquement depuis la collection Offres. Ne pas modifier ici.
   */
  offers?: (string | Offer)[] | null;
  mainImage?: (string | null) | Media;
  mainImageUrl?: string | null;
  images?:
    | {
        image?: (string | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Oui = afficher l'icône bus et le texte "Transfert inclus" sur la carte hôtel.
   */
  transferIncluded?: boolean | null;
  breakfastIncluded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer-packs".
 */
export interface OfferPack {
  id: string;
  title: string;
  /**
   * Auto-generated from title if left blank
   */
  slug?: string | null;
  /**
   * Sélectionnez une ou plusieurs destinations pour ce pack.
   */
  countries?: (string | Destination)[] | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainImage?: (string | null) | Media;
  mainImageUrl?: string | null;
  /**
   * Ajoutez plusieurs images secondaires pour le pack.
   */
  galleryImages?:
    | {
        image?: (string | null) | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  dates?: string | null;
  startDate?: string | null;
  /**
   * ex: "08:30"
   */
  departureTime?: string | null;
  durationDays?: number | null;
  /**
   * ex: "7 jours / 6 nuits"
   */
  duration?: string | null;
  price: string;
  priceAmount?: number | null;
  currency?: string | null;
  /**
   * ex: "Pack combiné"
   */
  badge?: string | null;
  badgeVariant?: ('info' | 'warning' | 'danger') | null;
  status?: ('available' | 'almost-full' | 'full') | null;
  /**
   * Créez autant de combinaisons que nécessaire. Exemple: combinaison 1 = hôtel Algérie + hôtel Tunisie.
   */
  hotelCombinations: {
    /**
     * ex: "Confort", "Premium", "Économique"
     */
    label: string;
    /**
     * ex: "85 000 DA". Ce prix est propre à la combinaison.
     */
    adultPriceLabel?: string | null;
    /**
     * Utilisé pour le calcul total de la réservation. Laissez vide pour fallback automatique.
     */
    adultPriceAmount?: number | null;
    /**
     * Définissez les prix enfants de cette combinaison (indépendants des hôtels).
     */
    childPriceBrackets?:
      | {
          /**
           * Ex: "2 – 4 ans"
           */
          label: string;
          minAge?: number | null;
          maxAge?: number | null;
          priceAmount: number;
          /**
           * Ex: "15 000 DA"
           */
          priceLabel?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Associez librement un pays et un hôtel pour chaque étape de la combinaison.
     */
    entries: {
      country: string;
      hotel: string | Hotel;
      /**
       * ex: "2 nuits"
       */
      stayDuration: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * Chaque ligne peut définir le texte affiché dans 'Ce qui est inclus' ainsi que son icône.
   */
  inclusions?:
    | {
        item: string;
        icon?: ('check' | 'plane' | 'hotel' | 'transfer' | 'assistance' | 'meal' | 'map' | 'calendar') | null;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ajoutez ici le programme du pack : jour, titre, description, lieux, repas et photos.
   */
  program?:
    | {
        /**
         * ex: "JOUR 1"
         */
        dayLabel: string;
        title: string;
        description?: string | null;
        locations?:
          | {
              place: string;
              id?: string | null;
            }[]
          | null;
        meals?:
          | {
              /**
               * ex: "Petit-déjeuner", "Dîner"
               */
              meal: string;
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image?: (string | null) | Media;
              imageUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        isLast?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: string;
  name: string;
  /**
   * Doit correspondre au champ country des offres, ex: Turquie
   */
  country: string;
  slug?: string | null;
  image?: (string | null) | Media;
  imageUrl?: string | null;
  /**
   * Catégorie libre (ex: afrique, europe, asie...). Si vide, la valeur 'tout' est appliquée.
   */
  category: string;
  cardDescription?: string | null;
  cardTags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Laisser vide pour utiliser automatiquement /listing?country=<country>
   */
  href?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  text: string;
  author: string;
  /**
   * e.g. "Septembre 2025"
   */
  date?: string | null;
  rating: number;
  type?: ('text' | 'video') | null;
  videoImage?: (string | null) | Media;
  videoImageUrl?: string | null;
  videoQuote?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modifiez ici uniquement les questions et les reponses de la FAQ. Le slider visuel du passeport reste fixe dans le frontend et n'est pas editable depuis le CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: string;
  text: string;
  image?: (string | null) | Media;
  imageUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-steps".
 */
export interface BookingStep {
  id: string;
  /**
   * e.g. "01."
   */
  num: string;
  title: string;
  description: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Demandes de réservation envoyées par les clients.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: string;
  fullName: string;
  phone: string;
  /**
   * Titre de l'offre concernée.
   */
  offerTitle?: string | null;
  offerId?: string | null;
  selectedHotel: string;
  adults: number;
  children?: number | null;
  /**
   * Montant total estimé affiché au client.
   */
  totalEstimated?: string | null;
  currency?: string | null;
  /**
   * Détails des tranches d'âge sélectionnées pour chaque enfant (JSON).
   */
  childDetails?: string | null;
  status?: ('new' | 'in-progress' | 'confirmed' | 'paid' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'offers';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'offer-packs';
        value: string | OfferPack;
      } | null)
    | ({
        relationTo: 'destinations';
        value: string | Destination;
      } | null)
    | ({
        relationTo: 'hotels';
        value: string | Hotel;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'features';
        value: string | Feature;
      } | null)
    | ({
        relationTo: 'booking-steps';
        value: string | BookingStep;
      } | null)
    | ({
        relationTo: 'reservations';
        value: string | Reservation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  cloudinaryPublicId?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  destination?: T;
  country?: T;
  flag?: T;
  flagMedia?: T;
  flagUrl?: T;
  region?: T;
  shortDescription?: T;
  description?: T;
  mainImage?: T;
  mainImageUrl?: T;
  detailGallery?:
    | T
    | {
        main?:
          | T
          | {
              image?: T;
              imageUrl?: T;
            };
        side01?:
          | T
          | {
              image?: T;
              imageUrl?: T;
            };
        side02?:
          | T
          | {
              image?: T;
              imageUrl?: T;
            };
        side03?:
          | T
          | {
              image?: T;
              imageUrl?: T;
            };
      };
  galleryImages?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  dates?: T;
  startDate?: T;
  endDate?: T;
  durationDays?: T;
  durationNights?: T;
  duration?: T;
  price?: T;
  priceAmount?: T;
  currency?: T;
  hotels?:
    | T
    | {
        hotel?: T;
        priceLabel?: T;
        priceAmount?: T;
        childPriceBrackets?:
          | T
          | {
              label?: T;
              minAge?: T;
              maxAge?: T;
              priceAmount?: T;
              priceLabel?: T;
              id?: T;
            };
        id?: T;
      };
  tag?: T;
  badge?: T;
  badgeVariant?: T;
  status?: T;
  showOnHomepage?: T;
  departureLocation?: T;
  location?: T;
  time?: T;
  metaDates?: T;
  metaDuration?: T;
  priceSummary?: T;
  priceCard?:
    | T
    | {
        description?: T;
        travellersLabel?: T;
        defaultAdults?: T;
        travellersText?: T;
        detailsTitle?: T;
        totalLabel?: T;
        reserveButtonLabel?: T;
        confirmationText?: T;
      };
  numberOfDays?: T;
  inclusions?:
    | T
    | {
        item?: T;
        icon?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  program?:
    | T
    | {
        dayLabel?: T;
        title?: T;
        description?: T;
        locations?:
          | T
          | {
              place?: T;
              id?: T;
            };
        meals?:
          | T
          | {
              meal?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              id?: T;
            };
        isLast?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer-packs_select".
 */
export interface OfferPacksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  countries?: T;
  shortDescription?: T;
  description?: T;
  mainImage?: T;
  mainImageUrl?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  dates?: T;
  startDate?: T;
  departureTime?: T;
  durationDays?: T;
  duration?: T;
  price?: T;
  priceAmount?: T;
  currency?: T;
  badge?: T;
  badgeVariant?: T;
  status?: T;
  hotelCombinations?:
    | T
    | {
        label?: T;
        adultPriceLabel?: T;
        adultPriceAmount?: T;
        childPriceBrackets?:
          | T
          | {
              label?: T;
              minAge?: T;
              maxAge?: T;
              priceAmount?: T;
              priceLabel?: T;
              id?: T;
            };
        entries?:
          | T
          | {
              country?: T;
              hotel?: T;
              stayDuration?: T;
              id?: T;
            };
        id?: T;
      };
  inclusions?:
    | T
    | {
        item?: T;
        icon?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  program?:
    | T
    | {
        dayLabel?: T;
        title?: T;
        description?: T;
        locations?:
          | T
          | {
              place?: T;
              id?: T;
            };
        meals?:
          | T
          | {
              meal?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              id?: T;
            };
        isLast?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  slug?: T;
  image?: T;
  imageUrl?: T;
  category?: T;
  cardDescription?: T;
  cardTags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  stars?: T;
  rating?: T;
  address?: T;
  city?: T;
  country?: T;
  dates?: T;
  offers?: T;
  mainImage?: T;
  mainImageUrl?: T;
  images?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  transferIncluded?: T;
  breakfastIncluded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  text?: T;
  author?: T;
  date?: T;
  rating?: T;
  type?: T;
  videoImage?: T;
  videoImageUrl?: T;
  videoQuote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  text?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-steps_select".
 */
export interface BookingStepsSelect<T extends boolean = true> {
  num?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  offerTitle?: T;
  offerId?: T;
  selectedHotel?: T;
  adults?: T;
  children?: T;
  totalEstimated?: T;
  currency?: T;
  childDetails?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: string;
  hero?: {
    /**
     * Image utilisee dans la banniere en haut de la page galerie.
     */
    background?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
  };
  /**
   * Chaque bloc correspond a un emplacement visible dans la grille de la section Malaisie.
   */
  malaisie?: {
    /**
     * Haut gauche
     */
    block01?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Grand bloc central
     */
    block02?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Haut droite
     */
    block03?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Bas gauche
     */
    block04?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Bas droite
     */
    block05?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Grand bloc bas gauche
     */
    block06?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Bas centre haut
     */
    block07?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Grand bloc bas droite
     */
    block08?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Bas centre bas
     */
    block09?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
  };
  /**
   * Chaque image correspond a un slide du carousel horizontal.
   */
  indonesie?: {
    slide01?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    slide02?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    slide03?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    slide04?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    slide05?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
  };
  /**
   * Chaque bloc correspond a un emplacement visible dans la grille de la section Zanzibar.
   */
  zanzibar?: {
    /**
     * Colonne gauche haut
     */
    block01?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne centre haut
     */
    block02?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne droite haut
     */
    block03?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne centre milieu
     */
    block04?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne gauche milieu
     */
    block05?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne droite milieu
     */
    block06?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne centre bas
     */
    block07?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne gauche bas
     */
    block08?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
    /**
     * Colonne droite bas
     */
    block09?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero?: {
    sky?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    logo?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    testimonialAvatar?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    taj?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    eiffel?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    petra?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    pyramids?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    statue?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    colosseum?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
    plane?: {
      image?: (string | null) | Media;
      imageUrl?: string | null;
      video?: (string | null) | Media;
      videoUrl?: string | null;
      alt?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-process-content".
 */
export interface BookingProcessContent {
  id: string;
  /**
   * Choisissez entre les 3 blocs texte actuels ou un carousel photo sur la partie droite.
   */
  layoutMode: 'text' | 'photos';
  /**
   * Le numero reste fixe dans le frontend. Seuls le titre et la description sont modifiables.
   */
  block1?: {
    title: string;
    description: string;
  };
  /**
   * Le numero reste fixe dans le frontend. Seuls le titre et la description sont modifiables.
   */
  block2?: {
    title: string;
    description: string;
  };
  /**
   * Le numero reste fixe dans le frontend. Seuls le titre et la description sont modifiables.
   */
  block3?: {
    title: string;
    description: string;
  };
  /**
   * Ajoutez entre 1 et 6 images en format portrait / reel (ratio 9:16) pour le carousel.
   */
  photoSlides?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        background?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
      };
  malaisie?:
    | T
    | {
        block01?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block02?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block03?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block04?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block05?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block06?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block07?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block08?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block09?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
      };
  indonesie?:
    | T
    | {
        slide01?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        slide02?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        slide03?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        slide04?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        slide05?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
      };
  zanzibar?:
    | T
    | {
        block01?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block02?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block03?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block04?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block05?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block06?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block07?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block08?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
        block09?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        sky?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        logo?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        testimonialAvatar?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        taj?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        eiffel?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        petra?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        pyramids?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        statue?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        colosseum?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
        plane?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              video?: T;
              videoUrl?: T;
              alt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-process-content_select".
 */
export interface BookingProcessContentSelect<T extends boolean = true> {
  layoutMode?: T;
  block1?:
    | T
    | {
        title?: T;
        description?: T;
      };
  block2?:
    | T
    | {
        title?: T;
        description?: T;
      };
  block3?:
    | T
    | {
        title?: T;
        description?: T;
      };
  photoSlides?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}